### PR TITLE
Fixed MySQL primary key issue with MySQL >= 5.7.3

### PR DESCRIPTION
**Pull request by Keeguon**
Self explanatory (also in sync w/ current ActiveRecord code).

### CODE REVIEW

**Comment by kares** [comment]
Thanks @Keeguon, is the change backwards compatible since AR-JDBC runs against older AR versions?

**Comment by Keeguon** [comment]
@kares Since it's mainly how the primary key is handled it has no impact moreover IMO it wasn't making a whole lot of sense for a primary key to be defaulted to NULL in MySQL. The change was made in AR 4.1 which means older versions don't support MySQL >= 5.7.3 natively and a monkey patch must be applied. Also, I did tests yesterday and also backported this to the 1.3 branch on my fork (if you want me to do a PR for this branch as well tell me) because I needed that for a project.

**Comment by kares** [comment]
Thanks for confirming. If you want to see it in next 1.3 release its preferable to open this against 1.3-stable branch - no need for this in that case as it will merge to master later. If you do so, please link the other PR here - your comment might be valuable for others.

**Comment by Keeguon** [comment]
Here's the PR for the 1-3-stable branch: https://github.com/jruby/activerecord-jdbc-adapter/pull/695

**Comment by kares** [comment]
will merge over from 1-3-stable (due #695), thanks for the contribution.

**Pull request closed without merging**
