### PR TITLE
insert_returning fails when the primary key is not the first column in postgresql

### PR DESCRIPTION
**Pull request by satyanash**
Add failing test for postgresql when primary key is not the first column when insert_returning.

### CODE REVIEW

**Comment by satyanash** [comment]
Only workaround right now seems to be `insert_returning: false`. This is `true` by default when >= Rails 5.

**Comment by dr-itz** [comment]
on it..basically I have a fix ready that I did for performance reasons. Need to rebase to 50-stable and test

**Comment by dr-itz** [comment]
Ok, pushed out a fix + your test on top of my #1040. It's Rails 5.0, but we need that fix all the way back there. Thanks for providing the testcase!

Basically what happened is that we forgot the PG specific `sql_for_insert` stuff from AR. We never notices since the JDBC driver automatically appends `RETURNING *` to inserts. So it always just worked when the first column was the PK. Now instead of fixing up the generated SQL, instead I rely on the JDBC API.

Thinking about it, I'll move your test case to the generic part so we can test with MySQL as well.

**Comment by dr-itz** [comment]
> Thinking about it, I'll move your test case to the generic part so we can test with MySQL as well.

Just checked, sqlite3 and mysql don't care, only PG is affected, so we're good.

@enebo @kares could you have a look at #1040?

**Comment by satyanash** [comment]
whoa that was _fast_. Thanks!

**Pull request closed without merging**
