### PR TITLE
Improve Derby on ActiveRecord 4.2

### PR DESCRIPTION
**Pull request by donv**
First attempt at fixing the cast_type for derby.  This looks like a general fix for all adapters not overriding adapter#columns.

### CODE REVIEW

**Comment by kares** [comment]
FYI I think that I will put these to **1-3-stable** as they seem just fine to have in the next stable release

**Comment by donv** [comment]
OK, changed the checks for AR42 to be evaluated at load time and define separate methods.

This PR actually fixes the travis run for DB=jdbc.  Should I activate these in travis?

**Comment by donv** [comment]
And, @kares , OK to merge?

**Comment by kares** [comment]
you should have commit rights, it would be best if you put these commits into **1-3-stable** branch (will merge into master eventually) ... so that it ends up in the next (1.3.18) release

than open a PR against that branch (if you have more work) if you want to verify all is travis-ci-green-ish

jdbc gets tricky from time-to-time but if it passes on 1-3-stable please go ahead ...

**Comment by donv** [comment]
@kares I am having trouble working with 1-3-stable due to the duplicate files with different casing.  I have the standard OS X case-insensitive file system.

Can I merge to master og you put them on 1-3-stable?  Pretty please :)

**Comment by kares** [comment]
@donv haven't you deal with those before https://github.com/jruby/activerecord-jdbc-adapter/issues/332#issuecomment-13884674 ?

**Comment by donv** [comment]
OK, cherry picked and committed on 1-3-stable branch.  Closing this.

**Pull request closed without merging**
