### PR TITLE
Update PostgreSQL JDBC driver to v42.2.5

### PR DESCRIPTION
**Pull request by aleksandrs-ledovskis**
Ref: https://github.com/jruby/activerecord-jdbc-adapter/issues/995

### CODE REVIEW

**Comment by enebo** [comment]
@aleksandrs-ledovskis ah your PR just exposed something 50.x, 51.x, and 52.x only work with Java 8+ so the Java 6 + 7 jars need not exist any more.  You can delete those and not add newer versions (master will be for Rails 6.0 but we can back port this PR).

**Comment by aleksandrs-ledovskis** [comment]
@enebo Thanks for feedback, I have removed JRE6/7 JARs. 

The commit was also rebased onto `50-stable`, as you seem to pull `-stable` branches into `master` and MRs usually target oldest supported Rails. Please correct me if this conclusion is incorrect - I will make further fixes promptly.

**Comment by enebo** [comment]
@aleksandrs-ledovskis my mistake.. 50-stable is proper place to rebase this but I guess our adapter gem which these jars are included is still used with the older AR release for <5.0 support.  So I guess we do still need the 6+7 jars :|

**Comment by aleksandrs-ledovskis** [comment]
@enebo No problem. I have put the JARs back 👌

**Comment by aleksandrs-ledovskis** [comment]
The CI is red, but that's due to active failures in base branch (`50-stable`) itself.

**Comment by dr-itz** [comment]
👍 that was on my todo list as well...

btw, I'm working on getting those branches green (again). Most failures are easy cherry-picks from master, except the view failures which are due to the old PG version on CI for 50-stable and 51-stable (Rails actually tests against something newer)

**Comment by enebo** [comment]
Just reran this on ci after last @dr-itz merge and I see some more strict syntax requirements in the few failing tests.

**Comment by dr-itz** [comment]
@enebo actually I think the problem is what Travis tested. It says "Merge 2c05c05 into ebea905" which is the jndi merge, not the latest 50-stable. I did a quick run with this rebased here:
https://travis-ci.org/dr-itz/activerecord-jdbc-adapter/builds/515339777
looks fine, no regressions against 50-stable, so I'd say this fine to merge

**Comment by enebo** [comment]
@dr-itz ok

**Comment by aleksandrs-ledovskis** [comment]
Thanks for accepting PR. Can this take a merge-train to `52-stable`?

**Comment by enebo** [comment]
@aleksandrs-ledovskis yeah I plan to do it today.

**Comment by enebo** [comment]
@aleksandrs-ledovskis done

**Comment by aleksandrs-ledovskis** [comment]
@enebo Thank you!

**Pull request merged**
