### PR TITLE
[as400] Fixed ordering when limit and offset present

### PR DESCRIPTION
**Pull request by rsov**
Re-wrote the query in `replace_limit_offset!` method in db2 adapter. SQL is simple to follow and it handles ordering

### CODE REVIEW

**Comment by kares** [comment]
thanks, will this work in other DB2 systems besides AS400? (I mean the 'regular' DB2 one can install)
could you please verify by running the suite ?

**Comment by rsov** [comment]
I tried to connect to the db2 side of our as400 but could not get it to work. But I'll give it a try once we figure out why its not working

**Comment by kares** [comment]
ping ... if you're really into having this in for next 1.3 release. isn't planned yet but its been a month or so.

**Comment by rsov** [comment]
@kares Sorry, I could not connect to DB2, only AS400. The tests that were originally failing are not passing but I am not sure what else it will effect

**Comment by rsov** [comment]
@kares Turns out there is no way I can test this. Its a product that needs purchasing and setting up. Currently we are running JDBC on AS400, because could not get the DB2 connection to work

**Comment by kares** [comment]
@rsov that's weird I had it installed just fine on a (virtual) Linux box. there should be a developer edition.
guess one needs to register though ... https://www-01.ibm.com/marketing/iwm/iwm/web/preLogin.do?source=swg-db2dtrial

**Comment by rsov** [comment]
@kares I did not know about this product. Thank you. Will look into it in a few days

**Comment by kares** [comment]
did a quick run, seems that tests run fine and actually 2 errors went away, thus put this in https://github.com/jruby/activerecord-jdbc-adapter/commit/15d7d1f60c80662e5d237503780c0621ae698224

**Pull request closed without merging**
