### PR TITLE
Add some test excludes

### PR DESCRIPTION
**Pull request by dr-itz**

### CODE REVIEW

**Comment by dr-itz** [comment]
Btw, once merged all the way to 52-stable, this should get 52-stable green, and hopefully in a stable way. There might be a few other tests with intermittent failures, but far less frequent than the time precision thing ;)

**Comment by kares** [comment]
@enebo looks good to me to be merged, the rounding seems like not AR-JDBC's fault (or low priority)
having a :green_heart: CI (at least for a branch or two) would be for the best.

**Comment by enebo** [comment]
@dr-itz sorry was a bit under the weather mon/tues.

**Comment by dr-itz** [comment]
@enebo thx. master is green 💚 🎉 , but it looks like you forgot to push 52-stable

**Comment by enebo** [comment]
@dr-itz yep...pushed now.

**Pull request merged**
