### PR TITLE
RFC: remove the PG result set wrapper

### PR DESCRIPTION
**Pull request by dr-itz**
* AR uses the OID to map to named types for which handlers are registered
* JDBC can return the named types with getColumnTypeName()
* For normal (non-array, non-rage, etc.) this already works
* by adding handler based on the name as well as the OID,
  getColumnTypeName() can be used for everything. OID based mapping
  is still required for SchemaStatements.
* loading additional types needs to be adapted to handle OIDs as well
  as type names.
* pgjdbc returns two additional type: 'serial' and 'bigserial'. They're
  just int4 and int8 with auto-increment on top
* only trick thing is "fmod". luckily this is only used for "numeric"
  and can be re-constructed by using getPrecision() and getScale()
* one test needs to be excluded because it checks for a message containing
  an OID (number) instead of name (string) we get now

See #965 

**NOTE**: this is against master because master is otherwise green. Would make sense to rebase against 50-stable. If it's any good that is :)

### CODE REVIEW

**Comment by rdubya** [comment]
I haven't looked at this stuff in a long time, but I thought the reason we needed the specific oid was because the type of data inside the array was linked to that. Does the name include that info?

**Comment by enebo** [comment]
@dr-itz looks like this creates one extra query for one test?  Personally, if @rdubya's concern is not an issue it would be great to remove the reflective hack since the jdbc adapter guys are not keen on exposing oid.

**Comment by dr-itz** [comment]
@rdubya Arrays are handled fine. They needed a bit of special code to register by their names as well. OID is unique, typname within typnamespace too. That reminds me that we need to look at the namespace too to be really correct (note that AR misses it too). I'll check..

@enebo No additional queries that I can see (well, except those done internally by pgjdbc, but they don't show). The only thing as far as testing goes is the exclude I added...and that is just because the message "...regclass..." doesn't match "...\d+..." 😉

**Comment by enebo** [comment]
@dr-itz I have not checked recently but I thought master was green and we appear to have on fail with this PR (extra query).

**Comment by dr-itz** [comment]
@enebo ah..that one is MySQL, so it's unrelated...it'll probably pass if you restart the job

**Comment by enebo** [comment]
@dr-itz can you reapply to 50-stable?  Looks like @rdubya question has been answered and your other PR was merged so things should be pretty much green on 50 now.

**Comment by dr-itz** [comment]
@enebo will do, but thinking about it a bit more, the namespace thing needs to be fixed before this is ready. It could possibly select the wrong type based on the name alone...the lookup needs to handle three cases:
* by OID for SchemaStatements. Check
* by name w/o namespace. Half-check; needs to make sure that only the right namespaces are searched in. Nothing big, just an additional WHERE
* by name w/ namespace (pgjdbc can return this). ToDo; split by ".", possibly unquote than have a query that joins the `pg_namespace` table. Seems easy enough

**Comment by enebo** [comment]
@dr-itz I am hoping to revv all 50+ releases this week.  So this can possibly go in for next point release unless you happen to solve this in next day or two.

**Comment by dr-itz** [comment]
@enebo I'm having some more time to look into it Thursday/Friday...currently I'm preparing some minor fixes for 51-stable and 52-stable...first PR soon(ish)

**Comment by dr-itz** [comment]
Ok, namespace handling implemented and rebased onto 50-stable. No regressions so far...

Note on merges: later versions of Rails changed the signature of `load_additional_types()` by dropping the first argument...that's all

**Comment by dr-itz** [comment]
https://travis-ci.org/dr-itz/activerecord-jdbc-adapter/builds/516662643

**Comment by mengu** [comment]
thank you very much for this @dr-itz.

**Pull request merged**
