### PR TITLE
[50-52, postgres] Add missing supports_x? methods

### PR DESCRIPTION
**Pull request by dr-itz**
This mostly makes sure that the tests for these features are
actually executed.

### CODE REVIEW

**Comment by enebo** [comment]
@dr-itz I have only seen 50-stable test come back but this causes fails with PS of postgresql because bulk_alter_table method is not defined.

**Comment by dr-itz** [comment]
`supports_bulk_alter?` is only supported on AR5.2, the rest should be ok

**Comment by enebo** [comment]
@dr-itz  no harm no foul.   I can just remove that from 50 and 51

**Comment by enebo** [comment]
@dr-itz done.  I somehow added whitespace in 52 and master after merge...so a little harm but I inflicted it :)

**Comment by dr-itz** [comment]
@enebo thanks

**Pull request merged**
