### PR TITLE
Added minimal implementation of PGconn with unescape_bytea

### LINKED ISSUE #651: Problem reading postgresql table with binary/bytea column
I'm trying to upgrade our project to Rails 4.2.1, and when I try to load data from a table with a bytea column, created using t.binary in the migration file, I get an error:

`uninitialized constant ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Bytea::PGconn`

I have tried this with both master and 1.3.6, with the same problem. A sample stack trace is:

```
        from /home/joconnor/.rvm/gems/jruby-1.7.20@xpesa/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/oid/bytea.rb:9:in `type_cast_from_database'
        from /home/joconnor/.rvm/gems/jruby-1.7.20@xpesa/gems/activerecord-4.2.1/lib/active_record/attribute.rb:104:in `type_cast'
        from /home/joconnor/.rvm/gems/jruby-1.7.20@xpesa/gems/activerecord-4.2.1/lib/active_record/attribute.rb:42:in `original_value'
        from /home/joconnor/.rvm/gems/jruby-1.7.20@xpesa/gems/activerecord-4.2.1/lib/active_record/attribute.rb:37:in `value'
        from /home/joconnor/.rvm/gems/jruby-1.7.20@xpesa/gems/activerecord-4.2.1/lib/active_record/attribute_set.rb:31:in `fetch_value'
        from /home/joconnor/.rvm/gems/jruby-1.7.20@xpesa/gems/activerecord-4.2.1/lib/active_record/attribute_methods/read.rb:93:in `_read_attribute'
        from /home/joconnor/.rvm/gems/jruby-1.7.20@xpesa/gems/activerecord-4.2.1/lib/active_record/attribute_methods/read.rb:87:in `read_attribute'
        from /home/joconnor/.rvm/gems/jruby-1.7.20@xpesa/gems/activerecord-4.2.1/lib/active_record/attribute_methods.rb:305:in `attribute_for_inspect'
        from /home/joconnor/.rvm/gems/jruby-1.7.20@xpesa/gems/activerecord-4.2.1/lib/active_record/core.rb:444:in `inspect'
        from /home/joconnor/.rvm/gems/jruby-1.7.20@xpesa/gems/activerecord-4.2.1/lib/active_record/core.rb:442:in `collect'
        from /home/joconnor/.rvm/gems/jruby-1.7.20@xpesa/gems/activerecord-4.2.1/lib/active_record/core.rb:442:in `inspect'
        from /home/joconnor/.rvm/gems/jruby-1.7.20@xpesa/gems/railties-4.2.1/lib/rails/commands/console.rb:110:in `start'
 ```

This was not a problem with Rails 4.1.6 or earlier.

Has anyone else seen this problem. Google was not helpful in this regard.

The fix is to implement PGconn.unescape_bytea, which is what I may end up doing.

### PR DESCRIPTION
**Pull request by donv**
To fix #651 and #652 .

### CODE REVIEW

**Comment by donv** [comment]
Before:

    380 tests, 608 assertions, 4 failures, 21 errors, 2 pendings, 72 omissions, 0 notifications

After:

    380 tests, 639 assertions, 4 failures, 17 errors, 2 pendings, 72 omissions, 0 notifications

4 errors fixed.  OK to merge?

**Comment by prathamesh-sonpatki** [comment]
:+1:

**Comment by kares** [comment]
Thanks Uwe, looks good however with jruby-pg around it's quite ugly to pollute their name-space ... we did moneky-patch AR previously so would you mind if I change that ?

also I'm not sure why you put up the 1.4 target ... I'd like to put it on 1-3-stable and then merge here so that it lands in next stable release (for 1.4 I would also move this code into native), thoughts?

**Comment by donv** [comment]
Hi @kares !

Thanks for looking at this.  Feel free to change as you see fit :smile: and put on the 1-3-stable as well.  I was unsure if 1-3-stable targeted AR 4.2.

I got an error using schema_plus without any implemented PGconn because the OID implementation for PostgreSQL is loaded then.  Not sure if this is intended, but it seems ARJDBC aims to use as much standard AR as possible, and AR uses PGconn directly.

**Comment by kares** [comment]
oh, you guys merged that already - well just go for it than - I do not have time to "play" around AR 4.2 compatibility hacks just be aware when introducing another :) ... planning a 1.4 pre-release from master.

**Comment by kares** [comment]
@donv OID was completely re-invented previously, AR "promised" mixins will be shareable ...but it's not :(

**Comment by donv** [comment]
I'd like everyone to play nice together, but it seems jruby-pg and ARJDBC are exclusive, right?  They should not be used together?  AR+ARJDBC or AR+jruby-pg, right?

**Comment by kares** [comment]
why would they be exclusive? ... I mean for AR they might be, but pg is not made solely for AR ...

**Comment by kares** [comment]
... you can hide the `PGConn` under `OID` module (for now) ... it should work since there's no `::PGConn`

**Comment by donv** [comment]
Oh.  I'm learning, then :)  How would you use jruby-pg with ARJDBC?

I'll move the PGconn class below the ActiveRecord::ConnectionAdapters::PostgreSQL::OID module.

**Comment by kares** [comment]
> I mean for AR they might be, but pg is not made solely for AR ...

... one can access DBs in different ways (along side with AR) - which is probably uncommon but possible

**Pull request merged**
