### PR TITLE
fix(mysql): fix dependency for jdbc-mysql

### PR DESCRIPTION
**Pull request by dr-itz**
Spotted by @mohamedhafez

### CODE REVIEW

**Comment by mohamedhafez** [comment]
@enebo or @headius, would you guys mind taking a look at this? It seems like jdbc-mysql has been unintentionally locked to versions 5.1.*, causing https://github.com/jruby/activerecord-jdbc-adapter/issues/1082. If that's indeed unintentional it would be really nice to get that fixed up!

**Comment by reidmorrison** [comment]
@enebo or @headius, would you mind please merging this PR, since it will really help out our JRuby production deployment? We have MySQL 8 in production and JRuby is still stuck on the MySQL 5.7 drivers, even though the new v8 drivers are available in the latest `jdbc-mysql`.

**Comment by enebo** [comment]
I will spind new releases this week.  Sorry I missed this one.  Thanks to @dr-itz again!

**Comment by enebo** [comment]
This has been updated for 52.x, 60.x, and 61.x.  Our build system is all for one and one for all so you will notice all gems were released in this project when only mysql gemspec was changed....Weird but the time to fix it is not time I want to take right now.

**Comment by reidmorrison** [comment]
Thank you @enebo, appreciate your help, the MySQL 8 JDBC drivers are working very well in production. :tada:

**Pull request merged**
