### PR TITLE
gemspec: Fixed typo

### PR DESCRIPTION
**Pull request by perlun**
I saw this on the Rubygems web page: https://rubygems.org/gems/jdbc-jtds

### CODE REVIEW

**Comment by kares** [comment]
this driver is pretty much dead for a few years now, so it won't get into RGs really, but thanks anyway.

**Comment by perlun** [comment]
> this driver is pretty much dead for a few years now, so it won't get into RGs really, but thanks anyway.

Yeah, but things might change. Who knows - there might be new `jtds` releases coming (even though it seems unlikely), so it makes sense to take in in nonetheless.

**Comment by kares** [comment]
on 1-3-stable https://github.com/jruby/activerecord-jdbc-adapter/commit/0146c116a7a0592e45a3182cd4279959478ffeb5 (will merge over to master after next release)

**Comment by perlun** [comment]
Thanks @kares!

**Pull request closed without merging**
