### PR TITLE
[postgres]: Support legacy binds

### PR DESCRIPTION
**Pull request by dr-itz**
Fixes:
* rails52:test/cases/adapter_test.rb#test_insert_update_delete_with_legacy

### CODE REVIEW

**Comment by dr-itz** [comment]
So...the NPE fix I'm still OK with, but..

Turns out sqlite3 has the same problem with legacy binds. So I wonder if the legacy binds
check should go to the generic code in ArJdbc::Abstract::DatabaseStatements?

Comments?

**Comment by kares** [comment]
its broken - likely for all in 5.x ... recall I tried to fix it but than it ended up being reverted.
its likely tricky to get right - would need to dig up history to recall context/details on what went on ...

**Comment by dr-itz** [comment]
Interesting...I'll do some digging to find out why it was problematic

(I just tried it in the generic code and it's simple enough...3 lines...but..)

**Comment by kares** [comment]
believe I also wanted it to do less garbage - ideally not to render aby binds if SQL debug isn't enabled

**Comment by enebo** [comment]
@dr-itz @kares so in 5.2 they realized they need to support legacy and re-added a test for it?  I don't see any legacy tests in 5.1.6 tests.

**Comment by dr-itz** [comment]
I think it works in AR 5.0 and 5.1 (but lacking tests), the breakage was during 5.2 development. My proposed fix is here: #911

**Comment by kares** [comment]
so with https://github.com/jruby/activerecord-jdbc-adapter/pull/911 this (postgres specific piece) is no longer needed, right?

**Comment by dr-itz** [comment]
Yes...closing this for #911

**Pull request closed without merging**
